name: pipeline

on: [push]

jobs:
  test-job:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12"]
    steps:
    - uses: actions/checkout@v4
    - name: Install uv and set the Python version
      uses: astral-sh/setup-uv@v5
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install the project
      run: uv sync --all-extras --dev
    - name: Test with pytest
      run: |
        uv run pytest --cov=./pyrff --cov-report term-missing pyrff/
    - name: Run dedicated coverage step
      run: |
        export NUMBA_DISABLE_JIT=1
        uv run pytest --cov=./pyrff --cov-report xml --cov-report term-missing pyrff/
    - name: Upload coverage
      uses: codecov/codecov-action@v5
      with:
        file: ./coverage.xml
        fail_ci_if_error: true
    - name: Test Wheel install and import
      run: |
        uv run python -m build
        uv run twine check dist/*
        cd dist
        pip install pyrff*.whl
        python -c "import pyrff; print(pyrff.__version__)"
