name: pipeline

on: [push]

jobs:
  test-job:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12"]
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        pip install flake8 pytest pytest-cov codecov wheel
        pip install -r requirements.txt
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings
        flake8 . --count --exit-zero --statistics
    - name: Test with pytest
      run: |
        pytest --cov=./pyrff --cov-report term-missing pyrff/
    - name: Run dedicated coverage step
      run: |
        export NUMBA_DISABLE_JIT=1
        pytest --cov=./pyrff --cov-report xml --cov-report term-missing pyrff/
    - name: Upload coverage
      uses: codecov/codecov-action@v5
      with:
        file: ./coverage.xml
        fail_ci_if_error: true
    - name: Test Wheel install and import
      run: |
        python setup.py bdist_wheel
        cd dist
        pip install pyrff*.whl
        python -c "import pyrff; print(pyrff.__version__)"
